# Generated by Django 4.2.4 on 2023-08-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lookup', '0003_rename_city_area_alter_area_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
