# Generated by Django 4.2.4 on 2023-08-22 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lookup', '0004_alter_code_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
    ]
